# 2022년 1월
SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.price*s.sales) as TOTAL_SALES
FROM BOOK as b
    JOIN AUTHOR as a ON b.AUTHOR_ID	 = a.AUTHOR_ID
    JOIN BOOK_SALES as s ON b.BOOK_ID = s.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY 1, 3
ORDER BY 1, 3 DESC